// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LobHubService.proto

package com.proto.LogiHubService;

public interface FailureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logi_hub.FailureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
