// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LobHubService.proto

package com.proto.LogiHubService;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logi_hub.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Mystatus = 1;</code>
   */
  java.lang.String getMystatus();
  /**
   * <code>string Mystatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getMystatusBytes();
}
