// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LobHubService.proto

package com.proto.LogiHubService;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logi_hub.StatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderid = 1;</code>
   */
  java.lang.String getOrderid();
  /**
   * <code>string orderid = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderidBytes();

  /**
   * <code>string clientname = 2;</code>
   */
  java.lang.String getClientname();
  /**
   * <code>string clientname = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientnameBytes();

  /**
   * <code>string mydelivery = 3;</code>
   */
  java.lang.String getMydelivery();
  /**
   * <code>string mydelivery = 3;</code>
   */
  com.google.protobuf.ByteString
      getMydeliveryBytes();
}
