// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockRoomService.proto

package com.proto.StockRoomService;

public interface AlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.StockRoomService.AlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
