// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockRoomService.proto

package com.proto.StockRoomService;

public interface AlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.StockRoomService.AlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string itemname = 1;</code>
   */
  java.lang.String getItemname();
  /**
   * <code>string itemname = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemnameBytes();

  /**
   * <code>int32 minStockLevel = 2;</code>
   */
  int getMinStockLevel();
}
