// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockRoomService.proto

package com.proto.StockRoomService;

/**
 * <pre>
 *DEFINE THE MESSAGE
 *Unary rpc
 * </pre>
 *
 * Protobuf type {@code com.proto.StockRoomService.OrderRequestt}
 */
public  final class OrderRequestt extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.proto.StockRoomService.OrderRequestt)
    OrderRequesttOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderRequestt.newBuilder() to construct.
  private OrderRequestt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderRequestt() {
    orderid_ = "";
    clientname_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderRequestt(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            orderid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clientname_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_OrderRequestt_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_OrderRequestt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.StockRoomService.OrderRequestt.class, com.proto.StockRoomService.OrderRequestt.Builder.class);
  }

  public static final int ORDERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object orderid_;
  /**
   * <code>string orderid = 1;</code>
   */
  public java.lang.String getOrderid() {
    java.lang.Object ref = orderid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderid_ = s;
      return s;
    }
  }
  /**
   * <code>string orderid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOrderidBytes() {
    java.lang.Object ref = orderid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object clientname_;
  /**
   * <code>string clientname = 2;</code>
   */
  public java.lang.String getClientname() {
    java.lang.Object ref = clientname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientname_ = s;
      return s;
    }
  }
  /**
   * <code>string clientname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClientnameBytes() {
    java.lang.Object ref = clientname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getOrderidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderid_);
    }
    if (!getClientnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientname_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getOrderidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderid_);
    }
    if (!getClientnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientname_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.StockRoomService.OrderRequestt)) {
      return super.equals(obj);
    }
    com.proto.StockRoomService.OrderRequestt other = (com.proto.StockRoomService.OrderRequestt) obj;

    boolean result = true;
    result = result && getOrderid()
        .equals(other.getOrderid());
    result = result && getClientname()
        .equals(other.getClientname());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORDERID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderid().hashCode();
    hash = (37 * hash) + CLIENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientname().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.StockRoomService.OrderRequestt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.StockRoomService.OrderRequestt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.StockRoomService.OrderRequestt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.StockRoomService.OrderRequestt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.StockRoomService.OrderRequestt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *DEFINE THE MESSAGE
   *Unary rpc
   * </pre>
   *
   * Protobuf type {@code com.proto.StockRoomService.OrderRequestt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.proto.StockRoomService.OrderRequestt)
      com.proto.StockRoomService.OrderRequesttOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_OrderRequestt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_OrderRequestt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.StockRoomService.OrderRequestt.class, com.proto.StockRoomService.OrderRequestt.Builder.class);
    }

    // Construct using com.proto.StockRoomService.OrderRequestt.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      orderid_ = "";

      clientname_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_OrderRequestt_descriptor;
    }

    @java.lang.Override
    public com.proto.StockRoomService.OrderRequestt getDefaultInstanceForType() {
      return com.proto.StockRoomService.OrderRequestt.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.StockRoomService.OrderRequestt build() {
      com.proto.StockRoomService.OrderRequestt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.StockRoomService.OrderRequestt buildPartial() {
      com.proto.StockRoomService.OrderRequestt result = new com.proto.StockRoomService.OrderRequestt(this);
      result.orderid_ = orderid_;
      result.clientname_ = clientname_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.StockRoomService.OrderRequestt) {
        return mergeFrom((com.proto.StockRoomService.OrderRequestt)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.StockRoomService.OrderRequestt other) {
      if (other == com.proto.StockRoomService.OrderRequestt.getDefaultInstance()) return this;
      if (!other.getOrderid().isEmpty()) {
        orderid_ = other.orderid_;
        onChanged();
      }
      if (!other.getClientname().isEmpty()) {
        clientname_ = other.clientname_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.StockRoomService.OrderRequestt parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.StockRoomService.OrderRequestt) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object orderid_ = "";
    /**
     * <code>string orderid = 1;</code>
     */
    public java.lang.String getOrderid() {
      java.lang.Object ref = orderid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orderid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderidBytes() {
      java.lang.Object ref = orderid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orderid = 1;</code>
     */
    public Builder setOrderid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string orderid = 1;</code>
     */
    public Builder clearOrderid() {
      
      orderid_ = getDefaultInstance().getOrderid();
      onChanged();
      return this;
    }
    /**
     * <code>string orderid = 1;</code>
     */
    public Builder setOrderidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientname_ = "";
    /**
     * <code>string clientname = 2;</code>
     */
    public java.lang.String getClientname() {
      java.lang.Object ref = clientname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientnameBytes() {
      java.lang.Object ref = clientname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientname = 2;</code>
     */
    public Builder setClientname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientname = 2;</code>
     */
    public Builder clearClientname() {
      
      clientname_ = getDefaultInstance().getClientname();
      onChanged();
      return this;
    }
    /**
     * <code>string clientname = 2;</code>
     */
    public Builder setClientnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientname_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.proto.StockRoomService.OrderRequestt)
  }

  // @@protoc_insertion_point(class_scope:com.proto.StockRoomService.OrderRequestt)
  private static final com.proto.StockRoomService.OrderRequestt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.StockRoomService.OrderRequestt();
  }

  public static com.proto.StockRoomService.OrderRequestt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderRequestt>
      PARSER = new com.google.protobuf.AbstractParser<OrderRequestt>() {
    @java.lang.Override
    public OrderRequestt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderRequestt(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderRequestt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderRequestt> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.StockRoomService.OrderRequestt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

