// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockRoomService.proto

package com.proto.StockRoomService;

public interface OrderRequesttOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.StockRoomService.OrderRequestt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderid = 1;</code>
   */
  java.lang.String getOrderid();
  /**
   * <code>string orderid = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderidBytes();

  /**
   * <code>string clientname = 2;</code>
   */
  java.lang.String getClientname();
  /**
   * <code>string clientname = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientnameBytes();
}
