// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockRoomService.proto

package com.proto.StockRoomService;

public interface ReadyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.StockRoomService.ReadyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string OrderStatus = 1;</code>
   */
  java.lang.String getOrderStatus();
  /**
   * <code>string OrderStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderStatusBytes();
}
