// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockRoomService.proto

package com.proto.StockRoomService;

public interface StockSupplyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.StockRoomService.StockSupplyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float result = 1;</code>
   */
  float getResult();

  /**
   * <code>string mysupply = 2;</code>
   */
  java.lang.String getMysupply();
  /**
   * <code>string mysupply = 2;</code>
   */
  com.google.protobuf.ByteString
      getMysupplyBytes();
}
