// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockRoomService.proto

package com.proto.StockRoomService;

/**
 * <pre>
 *Stocksupply- Responsible to insert itens into stock. It should do the addition.
 * </pre>
 *
 * Protobuf type {@code com.proto.StockRoomService.StockSupplyRequest}
 */
public  final class StockSupplyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.proto.StockRoomService.StockSupplyRequest)
    StockSupplyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StockSupplyRequest.newBuilder() to construct.
  private StockSupplyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StockSupplyRequest() {
    currentQty_ = 0F;
    inputQty_ = 0F;
    operation_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StockSupplyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            currentQty_ = input.readFloat();
            break;
          }
          case 21: {

            inputQty_ = input.readFloat();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            operation_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_StockSupplyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_StockSupplyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.StockRoomService.StockSupplyRequest.class, com.proto.StockRoomService.StockSupplyRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code com.proto.StockRoomService.StockSupplyRequest.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADDITION = 0;</code>
     */
    ADDITION(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ADDITION = 0;</code>
     */
    public static final int ADDITION_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operation valueOf(int value) {
      return forNumber(value);
    }

    public static Operation forNumber(int value) {
      switch (value) {
        case 0: return ADDITION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.proto.StockRoomService.StockSupplyRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.proto.StockRoomService.StockSupplyRequest.Operation)
  }

  public static final int CURRENTQTY_FIELD_NUMBER = 1;
  private float currentQty_;
  /**
   * <code>float currentQty = 1;</code>
   */
  public float getCurrentQty() {
    return currentQty_;
  }

  public static final int INPUTQTY_FIELD_NUMBER = 2;
  private float inputQty_;
  /**
   * <code>float inputQty = 2;</code>
   */
  public float getInputQty() {
    return inputQty_;
  }

  public static final int OPERATION_FIELD_NUMBER = 3;
  private int operation_;
  /**
   * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
   */
  public int getOperationValue() {
    return operation_;
  }
  /**
   * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
   */
  public com.proto.StockRoomService.StockSupplyRequest.Operation getOperation() {
    @SuppressWarnings("deprecation")
    com.proto.StockRoomService.StockSupplyRequest.Operation result = com.proto.StockRoomService.StockSupplyRequest.Operation.valueOf(operation_);
    return result == null ? com.proto.StockRoomService.StockSupplyRequest.Operation.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentQty_ != 0F) {
      output.writeFloat(1, currentQty_);
    }
    if (inputQty_ != 0F) {
      output.writeFloat(2, inputQty_);
    }
    if (operation_ != com.proto.StockRoomService.StockSupplyRequest.Operation.ADDITION.getNumber()) {
      output.writeEnum(3, operation_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentQty_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, currentQty_);
    }
    if (inputQty_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, inputQty_);
    }
    if (operation_ != com.proto.StockRoomService.StockSupplyRequest.Operation.ADDITION.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, operation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.StockRoomService.StockSupplyRequest)) {
      return super.equals(obj);
    }
    com.proto.StockRoomService.StockSupplyRequest other = (com.proto.StockRoomService.StockSupplyRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getCurrentQty())
        == java.lang.Float.floatToIntBits(
            other.getCurrentQty()));
    result = result && (
        java.lang.Float.floatToIntBits(getInputQty())
        == java.lang.Float.floatToIntBits(
            other.getInputQty()));
    result = result && operation_ == other.operation_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTQTY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCurrentQty());
    hash = (37 * hash) + INPUTQTY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getInputQty());
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + operation_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.StockRoomService.StockSupplyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.StockRoomService.StockSupplyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Stocksupply- Responsible to insert itens into stock. It should do the addition.
   * </pre>
   *
   * Protobuf type {@code com.proto.StockRoomService.StockSupplyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.proto.StockRoomService.StockSupplyRequest)
      com.proto.StockRoomService.StockSupplyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_StockSupplyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_StockSupplyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.StockRoomService.StockSupplyRequest.class, com.proto.StockRoomService.StockSupplyRequest.Builder.class);
    }

    // Construct using com.proto.StockRoomService.StockSupplyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentQty_ = 0F;

      inputQty_ = 0F;

      operation_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.StockRoomService.StockRoomServiceImpl.internal_static_com_proto_StockRoomService_StockSupplyRequest_descriptor;
    }

    @java.lang.Override
    public com.proto.StockRoomService.StockSupplyRequest getDefaultInstanceForType() {
      return com.proto.StockRoomService.StockSupplyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.StockRoomService.StockSupplyRequest build() {
      com.proto.StockRoomService.StockSupplyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.StockRoomService.StockSupplyRequest buildPartial() {
      com.proto.StockRoomService.StockSupplyRequest result = new com.proto.StockRoomService.StockSupplyRequest(this);
      result.currentQty_ = currentQty_;
      result.inputQty_ = inputQty_;
      result.operation_ = operation_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.StockRoomService.StockSupplyRequest) {
        return mergeFrom((com.proto.StockRoomService.StockSupplyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.StockRoomService.StockSupplyRequest other) {
      if (other == com.proto.StockRoomService.StockSupplyRequest.getDefaultInstance()) return this;
      if (other.getCurrentQty() != 0F) {
        setCurrentQty(other.getCurrentQty());
      }
      if (other.getInputQty() != 0F) {
        setInputQty(other.getInputQty());
      }
      if (other.operation_ != 0) {
        setOperationValue(other.getOperationValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.StockRoomService.StockSupplyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.StockRoomService.StockSupplyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float currentQty_ ;
    /**
     * <code>float currentQty = 1;</code>
     */
    public float getCurrentQty() {
      return currentQty_;
    }
    /**
     * <code>float currentQty = 1;</code>
     */
    public Builder setCurrentQty(float value) {
      
      currentQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float currentQty = 1;</code>
     */
    public Builder clearCurrentQty() {
      
      currentQty_ = 0F;
      onChanged();
      return this;
    }

    private float inputQty_ ;
    /**
     * <code>float inputQty = 2;</code>
     */
    public float getInputQty() {
      return inputQty_;
    }
    /**
     * <code>float inputQty = 2;</code>
     */
    public Builder setInputQty(float value) {
      
      inputQty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float inputQty = 2;</code>
     */
    public Builder clearInputQty() {
      
      inputQty_ = 0F;
      onChanged();
      return this;
    }

    private int operation_ = 0;
    /**
     * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
     */
    public Builder setOperationValue(int value) {
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
     */
    public com.proto.StockRoomService.StockSupplyRequest.Operation getOperation() {
      @SuppressWarnings("deprecation")
      com.proto.StockRoomService.StockSupplyRequest.Operation result = com.proto.StockRoomService.StockSupplyRequest.Operation.valueOf(operation_);
      return result == null ? com.proto.StockRoomService.StockSupplyRequest.Operation.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
     */
    public Builder setOperation(com.proto.StockRoomService.StockSupplyRequest.Operation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      operation_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.proto.StockRoomService.StockSupplyRequest)
  }

  // @@protoc_insertion_point(class_scope:com.proto.StockRoomService.StockSupplyRequest)
  private static final com.proto.StockRoomService.StockSupplyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.StockRoomService.StockSupplyRequest();
  }

  public static com.proto.StockRoomService.StockSupplyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StockSupplyRequest>
      PARSER = new com.google.protobuf.AbstractParser<StockSupplyRequest>() {
    @java.lang.Override
    public StockSupplyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StockSupplyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StockSupplyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StockSupplyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.StockRoomService.StockSupplyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

