// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockRoomService.proto

package com.proto.StockRoomService;

public interface StockSupplyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.StockRoomService.StockSupplyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float currentQty = 1;</code>
   */
  float getCurrentQty();

  /**
   * <code>float inputQty = 2;</code>
   */
  float getInputQty();

  /**
   * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.com.proto.StockRoomService.StockSupplyRequest.Operation operation = 3;</code>
   */
  com.proto.StockRoomService.StockSupplyRequest.Operation getOperation();
}
