// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SalesService.proto

package com.proto.salesService;

public final class DemoSalesServiceImpl {
  private DemoSalesServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesService_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesService_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesService_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesService_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesService_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesService_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesService_PaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesService_PaymentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesService_FeedbackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesService_FeedbackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salesService_FeedbackResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_salesService_FeedbackResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SalesService.proto\022\014salesService\"\204\001\n\014O" +
      "rderRequest\022\020\n\010clientid\030\001 \001(\t\022\017\n\007orderid" +
      "\030\002 \001(\t\022\023\n\013phonenumber\030\003 \001(\t\022\025\n\rpurchasep" +
      "rice\030\004 \001(\001\022\023\n\013productname\030\005 \001(\t\022\020\n\010quant" +
      "ity\030\006 \001(\005\"\"\n\rOrderResponse\022\021\n\tMymessage\030" +
      "\001 \001(\t\"K\n\016PaymentRequest\022\017\n\007orderid\030\001 \001(\t" +
      "\022\022\n\nclientname\030\002 \001(\t\022\024\n\014paymenttotal\030\003 \001" +
      "(\001\"(\n\017PaymentResponse\022\025\n\rpaymentstatus\030\001" +
      " \001(\t\")\n\017FeedbackRequest\022\026\n\016feedbackClien" +
      "t\030\001 \001(\t\"#\n\020FeedbackResponse\022\017\n\007message\030\001" +
      " \001(\t2\370\001\n\014SalesService\022H\n\tSendOrder\022\032.sal" +
      "esService.OrderRequest\032\033.salesService.Or" +
      "derResponse\"\000(\001\022M\n\014CheckPayment\022\034.salesS" +
      "ervice.PaymentRequest\032\035.salesService.Pay" +
      "mentResponse\"\000\022O\n\010Feedback\022\035.salesServic" +
      "e.FeedbackRequest\032\036.salesService.Feedbac" +
      "kResponse\"\000(\0010\001B0\n\026com.proto.salesServic" +
      "eB\024DemoSalesServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_salesService_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_salesService_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesService_OrderRequest_descriptor,
        new java.lang.String[] { "Clientid", "Orderid", "Phonenumber", "Purchaseprice", "Productname", "Quantity", });
    internal_static_salesService_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_salesService_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesService_OrderResponse_descriptor,
        new java.lang.String[] { "Mymessage", });
    internal_static_salesService_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_salesService_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesService_PaymentRequest_descriptor,
        new java.lang.String[] { "Orderid", "Clientname", "Paymenttotal", });
    internal_static_salesService_PaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_salesService_PaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesService_PaymentResponse_descriptor,
        new java.lang.String[] { "Paymentstatus", });
    internal_static_salesService_FeedbackRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_salesService_FeedbackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesService_FeedbackRequest_descriptor,
        new java.lang.String[] { "FeedbackClient", });
    internal_static_salesService_FeedbackResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_salesService_FeedbackResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_salesService_FeedbackResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
