// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SalesService.proto

package com.proto.salesService;

public interface FeedbackRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesService.FeedbackRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string feedbackClient = 1;</code>
   */
  java.lang.String getFeedbackClient();
  /**
   * <code>string feedbackClient = 1;</code>
   */
  com.google.protobuf.ByteString
      getFeedbackClientBytes();
}
