// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SalesService.proto

package com.proto.salesService;

/**
 * <pre>
 *Server Streaming RPC: is a type of RPC where the client sends a request to the server and the server responds with a sequence
 * of messages. The SendOrder method fits this pattern because the client sends a request and the server responds with a
 *  confirmation message for each product in the order.
 * </pre>
 *
 * Protobuf type {@code salesService.OrderRequest}
 */
public  final class OrderRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:salesService.OrderRequest)
    OrderRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderRequest.newBuilder() to construct.
  private OrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderRequest() {
    clientid_ = "";
    orderid_ = "";
    phonenumber_ = "";
    purchaseprice_ = 0D;
    productname_ = "";
    quantity_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            orderid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            phonenumber_ = s;
            break;
          }
          case 33: {

            purchaseprice_ = input.readDouble();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            productname_ = s;
            break;
          }
          case 48: {

            quantity_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.proto.salesService.DemoSalesServiceImpl.internal_static_salesService_OrderRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.proto.salesService.DemoSalesServiceImpl.internal_static_salesService_OrderRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.proto.salesService.OrderRequest.class, com.proto.salesService.OrderRequest.Builder.class);
  }

  public static final int CLIENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientid_;
  /**
   * <code>string clientid = 1;</code>
   */
  public java.lang.String getClientid() {
    java.lang.Object ref = clientid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientid_ = s;
      return s;
    }
  }
  /**
   * <code>string clientid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClientidBytes() {
    java.lang.Object ref = clientid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDERID_FIELD_NUMBER = 2;
  private volatile java.lang.Object orderid_;
  /**
   * <code>string orderid = 2;</code>
   */
  public java.lang.String getOrderid() {
    java.lang.Object ref = orderid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orderid_ = s;
      return s;
    }
  }
  /**
   * <code>string orderid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOrderidBytes() {
    java.lang.Object ref = orderid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orderid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUMBER_FIELD_NUMBER = 3;
  private volatile java.lang.Object phonenumber_;
  /**
   * <code>string phonenumber = 3;</code>
   */
  public java.lang.String getPhonenumber() {
    java.lang.Object ref = phonenumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phonenumber_ = s;
      return s;
    }
  }
  /**
   * <code>string phonenumber = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPhonenumberBytes() {
    java.lang.Object ref = phonenumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phonenumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PURCHASEPRICE_FIELD_NUMBER = 4;
  private double purchaseprice_;
  /**
   * <code>double purchaseprice = 4;</code>
   */
  public double getPurchaseprice() {
    return purchaseprice_;
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object productname_;
  /**
   * <code>string productname = 5;</code>
   */
  public java.lang.String getProductname() {
    java.lang.Object ref = productname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productname_ = s;
      return s;
    }
  }
  /**
   * <code>string productname = 5;</code>
   */
  public com.google.protobuf.ByteString
      getProductnameBytes() {
    java.lang.Object ref = productname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 6;
  private int quantity_;
  /**
   * <code>int32 quantity = 6;</code>
   */
  public int getQuantity() {
    return quantity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientid_);
    }
    if (!getOrderidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderid_);
    }
    if (!getPhonenumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phonenumber_);
    }
    if (purchaseprice_ != 0D) {
      output.writeDouble(4, purchaseprice_);
    }
    if (!getProductnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, productname_);
    }
    if (quantity_ != 0) {
      output.writeInt32(6, quantity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientid_);
    }
    if (!getOrderidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderid_);
    }
    if (!getPhonenumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phonenumber_);
    }
    if (purchaseprice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, purchaseprice_);
    }
    if (!getProductnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, productname_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, quantity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.proto.salesService.OrderRequest)) {
      return super.equals(obj);
    }
    com.proto.salesService.OrderRequest other = (com.proto.salesService.OrderRequest) obj;

    boolean result = true;
    result = result && getClientid()
        .equals(other.getClientid());
    result = result && getOrderid()
        .equals(other.getOrderid());
    result = result && getPhonenumber()
        .equals(other.getPhonenumber());
    result = result && (
        java.lang.Double.doubleToLongBits(getPurchaseprice())
        == java.lang.Double.doubleToLongBits(
            other.getPurchaseprice()));
    result = result && getProductname()
        .equals(other.getProductname());
    result = result && (getQuantity()
        == other.getQuantity());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientid().hashCode();
    hash = (37 * hash) + ORDERID_FIELD_NUMBER;
    hash = (53 * hash) + getOrderid().hashCode();
    hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPhonenumber().hashCode();
    hash = (37 * hash) + PURCHASEPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPurchaseprice()));
    hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductname().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.proto.salesService.OrderRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.salesService.OrderRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.salesService.OrderRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.salesService.OrderRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.salesService.OrderRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.proto.salesService.OrderRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.proto.salesService.OrderRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.salesService.OrderRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.salesService.OrderRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.proto.salesService.OrderRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.proto.salesService.OrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.proto.salesService.OrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.proto.salesService.OrderRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Server Streaming RPC: is a type of RPC where the client sends a request to the server and the server responds with a sequence
   * of messages. The SendOrder method fits this pattern because the client sends a request and the server responds with a
   *  confirmation message for each product in the order.
   * </pre>
   *
   * Protobuf type {@code salesService.OrderRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:salesService.OrderRequest)
      com.proto.salesService.OrderRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.salesService.DemoSalesServiceImpl.internal_static_salesService_OrderRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.salesService.DemoSalesServiceImpl.internal_static_salesService_OrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.salesService.OrderRequest.class, com.proto.salesService.OrderRequest.Builder.class);
    }

    // Construct using com.proto.salesService.OrderRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientid_ = "";

      orderid_ = "";

      phonenumber_ = "";

      purchaseprice_ = 0D;

      productname_ = "";

      quantity_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.proto.salesService.DemoSalesServiceImpl.internal_static_salesService_OrderRequest_descriptor;
    }

    @java.lang.Override
    public com.proto.salesService.OrderRequest getDefaultInstanceForType() {
      return com.proto.salesService.OrderRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.proto.salesService.OrderRequest build() {
      com.proto.salesService.OrderRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.proto.salesService.OrderRequest buildPartial() {
      com.proto.salesService.OrderRequest result = new com.proto.salesService.OrderRequest(this);
      result.clientid_ = clientid_;
      result.orderid_ = orderid_;
      result.phonenumber_ = phonenumber_;
      result.purchaseprice_ = purchaseprice_;
      result.productname_ = productname_;
      result.quantity_ = quantity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.proto.salesService.OrderRequest) {
        return mergeFrom((com.proto.salesService.OrderRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.proto.salesService.OrderRequest other) {
      if (other == com.proto.salesService.OrderRequest.getDefaultInstance()) return this;
      if (!other.getClientid().isEmpty()) {
        clientid_ = other.clientid_;
        onChanged();
      }
      if (!other.getOrderid().isEmpty()) {
        orderid_ = other.orderid_;
        onChanged();
      }
      if (!other.getPhonenumber().isEmpty()) {
        phonenumber_ = other.phonenumber_;
        onChanged();
      }
      if (other.getPurchaseprice() != 0D) {
        setPurchaseprice(other.getPurchaseprice());
      }
      if (!other.getProductname().isEmpty()) {
        productname_ = other.productname_;
        onChanged();
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.proto.salesService.OrderRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.proto.salesService.OrderRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientid_ = "";
    /**
     * <code>string clientid = 1;</code>
     */
    public java.lang.String getClientid() {
      java.lang.Object ref = clientid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientidBytes() {
      java.lang.Object ref = clientid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientid = 1;</code>
     */
    public Builder setClientid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientid = 1;</code>
     */
    public Builder clearClientid() {
      
      clientid_ = getDefaultInstance().getClientid();
      onChanged();
      return this;
    }
    /**
     * <code>string clientid = 1;</code>
     */
    public Builder setClientidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object orderid_ = "";
    /**
     * <code>string orderid = 2;</code>
     */
    public java.lang.String getOrderid() {
      java.lang.Object ref = orderid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string orderid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrderidBytes() {
      java.lang.Object ref = orderid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string orderid = 2;</code>
     */
    public Builder setOrderid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      orderid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string orderid = 2;</code>
     */
    public Builder clearOrderid() {
      
      orderid_ = getDefaultInstance().getOrderid();
      onChanged();
      return this;
    }
    /**
     * <code>string orderid = 2;</code>
     */
    public Builder setOrderidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      orderid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phonenumber_ = "";
    /**
     * <code>string phonenumber = 3;</code>
     */
    public java.lang.String getPhonenumber() {
      java.lang.Object ref = phonenumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phonenumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string phonenumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhonenumberBytes() {
      java.lang.Object ref = phonenumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phonenumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string phonenumber = 3;</code>
     */
    public Builder setPhonenumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      phonenumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string phonenumber = 3;</code>
     */
    public Builder clearPhonenumber() {
      
      phonenumber_ = getDefaultInstance().getPhonenumber();
      onChanged();
      return this;
    }
    /**
     * <code>string phonenumber = 3;</code>
     */
    public Builder setPhonenumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      phonenumber_ = value;
      onChanged();
      return this;
    }

    private double purchaseprice_ ;
    /**
     * <code>double purchaseprice = 4;</code>
     */
    public double getPurchaseprice() {
      return purchaseprice_;
    }
    /**
     * <code>double purchaseprice = 4;</code>
     */
    public Builder setPurchaseprice(double value) {
      
      purchaseprice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double purchaseprice = 4;</code>
     */
    public Builder clearPurchaseprice() {
      
      purchaseprice_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object productname_ = "";
    /**
     * <code>string productname = 5;</code>
     */
    public java.lang.String getProductname() {
      java.lang.Object ref = productname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productname = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProductnameBytes() {
      java.lang.Object ref = productname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productname = 5;</code>
     */
    public Builder setProductname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productname = 5;</code>
     */
    public Builder clearProductname() {
      
      productname_ = getDefaultInstance().getProductname();
      onChanged();
      return this;
    }
    /**
     * <code>string productname = 5;</code>
     */
    public Builder setProductnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productname_ = value;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 6;</code>
     */
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 6;</code>
     */
    public Builder setQuantity(int value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 6;</code>
     */
    public Builder clearQuantity() {
      
      quantity_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:salesService.OrderRequest)
  }

  // @@protoc_insertion_point(class_scope:salesService.OrderRequest)
  private static final com.proto.salesService.OrderRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.proto.salesService.OrderRequest();
  }

  public static com.proto.salesService.OrderRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderRequest>
      PARSER = new com.google.protobuf.AbstractParser<OrderRequest>() {
    @java.lang.Override
    public OrderRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.proto.salesService.OrderRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

