// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SalesService.proto

package com.proto.salesService;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesService.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientid = 1;</code>
   */
  java.lang.String getClientid();
  /**
   * <code>string clientid = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientidBytes();

  /**
   * <code>string orderid = 2;</code>
   */
  java.lang.String getOrderid();
  /**
   * <code>string orderid = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderidBytes();

  /**
   * <code>string phonenumber = 3;</code>
   */
  java.lang.String getPhonenumber();
  /**
   * <code>string phonenumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getPhonenumberBytes();

  /**
   * <code>double purchaseprice = 4;</code>
   */
  double getPurchaseprice();

  /**
   * <code>string productname = 5;</code>
   */
  java.lang.String getProductname();
  /**
   * <code>string productname = 5;</code>
   */
  com.google.protobuf.ByteString
      getProductnameBytes();

  /**
   * <code>int32 quantity = 6;</code>
   */
  int getQuantity();
}
