// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SalesService.proto

package com.proto.salesService;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesService.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Mymessage = 1;</code>
   */
  java.lang.String getMymessage();
  /**
   * <code>string Mymessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getMymessageBytes();
}
