// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SalesService.proto

package com.proto.salesService;

public interface PaymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesService.PaymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderid = 1;</code>
   */
  java.lang.String getOrderid();
  /**
   * <code>string orderid = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderidBytes();

  /**
   * <code>string clientname = 2;</code>
   */
  java.lang.String getClientname();
  /**
   * <code>string clientname = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientnameBytes();

  /**
   * <code>double paymenttotal = 3;</code>
   */
  double getPaymenttotal();
}
