// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SalesService.proto

package com.proto.salesService;

public interface PaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salesService.PaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string paymentstatus = 1;</code>
   */
  java.lang.String getPaymentstatus();
  /**
   * <code>string paymentstatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getPaymentstatusBytes();
}
